#!/bin/sh
# ~/.ssh/rc

WEBHOOK_URL=""
SERVER_TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")
SERVER_HOSTNAME=$(hostname)
SRC_IP="${SSH_CONNECTION%% *}"
MESSAGE="<@348121438169071618> :shell:\\nUser \`$USER\` **has logged on over SSH from** \`$SRC_IP\` on \`$SERVER_HOSTNAME\`\\nServer Time: \`$SERVER_TIME\`"

curl -s -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" "$WEBHOOK_URL" >/dev/null 2>&1 &
