" shared vimrc for service users
" .vimrc
set autoindent
set smartindent
set tabstop=4 softtabstop=0
set shiftwidth=4 smarttab
set expandtab
syntax on
set number

" Disable error sound
set belloff=all

" Cosmetic
colorscheme default
