#!/bin/sh
# /etc/ssh/sshrc

WEBHOOK_URL="" # ADD URL HERE
LOG_TAG_PREFIX="automation"
LOG_TAG="sshrc"

SERVER_TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")
SRC_IP="${SSH_CONNECTION%% *}"

if [ -n "$SSH_TTY" ]; then
    MESSAGE="<@348121438169071618> :desktop: :shell:\\nUser \`$USER\` **has logged on over SSH from** \`$SRC_IP\`\\nServer Time: \`$SERVER_TIME\`"
    LOG_MESSAGE="$USER has logged on over SSH from $SRC_IP"
else
    MESSAGE=":floppy_disk: Non-interactive SSH command by \`$USER\` from \`$SRC_IP\`\\nServer Time: \`$SERVER_TIME\`"
    LOG_MESSAGE="$USER has run a non-interactive SSH command from $SRC_IP"
fi

logger -t "$LOG_TAG_PREFIX.$LOG_TAG" "$LOG_MESSAGE"
curl -s -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" "$WEBHOOK_URL" >/dev/null 2>&1 &
