#!/bin/sh
SERVER_TIME=$(date +"%Y-%m-%d %H:%M:%S %Z")
WEBHOOK_URL=""
MESSAGE="<@348121438169071618> :desktop: :shell:\\nUser \`$USER\` **has logged on over SSH from** \`${SSH_CONNECTION%% *}\`\\nServer Time: \`$SERVER_TIME\`"

curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"${MESSAGE}\"}" "$WEBHOOK_URL"
